### ISSUE TITLE
Missing things to translate

### ISSUE THREAD

**Issue by Aides123** [DavidTheExplorer/EmployMe#120]
Hey, I've been using the plugin for a while now and found things missing for translation.

Plugin prefix, "error".
![image](https://user-images.githubusercontent.com/23367220/148996991-3b251383-e84d-4047-b850-68e32c0121e0.png)

**Comment by DavidTheExplorer** [comment]
Hello, the prefix of the plugin will be translatable in the next update!
Please let me know if that's what you're concerned about.

**Comment by Aides123** [comment]
That was the point, thanks! <3
