### ISSUE TITLE
Round player's balance to 2 decimals

### ISSUE THREAD

**Issue by kohle** [DavidTheExplorer/EmployMe#123]
It looks like the player's balance is not formatted before being sent, causing really long messages like this:

![image](https://user-images.githubusercontent.com/892288/149596343-10f04a51-c823-44e4-83f6-4242886c84fd.png)

**Comment by DavidTheExplorer** [comment]
Thank you for reporting, I will update this issue once the next version is released - where this problem will be solved :)

**Comment by DavidTheExplorer** [comment]
Fixed in 4e8d414 and I just released an update that contains it 👍
