### ISSUE TITLE
Plugin lost Stacks

### ISSUE THREAD

**Issue by Leahcimkrob** [DavidTheExplorer/EmployMe#135]
If we have more than 54 stacks on 2 offers, only 50 stacks will be transferred to the customer, everything over 50 stacks will be lost.

**Comment by DavidTheExplorer** [comment]
Hello, can you elaborate? I'm working on the premium version and want to solve this asap. 
Can you please provide a concrete example?

**Comment by Leahcimkrob** [comment]
For example, if you need 54 stacks, you will only get 50 stacks from the plugin via /myitems. The other 4 stacks disappear
I had already written with you on Discord that we use the source code from your github through our dev, the error is already fixed as I see it.

**Comment by DavidTheExplorer** [comment]
This issue has been fixed in the premium version by making all containers(and the job board) infinite :)
I'm really sorry for the inconvenience.
