### ISSUE TITLE
[Suggestions]

### ISSUE THREAD

**Issue by 849025143** [DavidTheExplorer/EmployMe#76]
I very like this plugin. And...here are some of my suggestions, if you feel necessary.Thanks.

1. Support the use of items as rewards
2. Enable the server to publish tasks, like offer a reward

**Comment by DavidTheExplorer** [comment]
Hello!
1. You can offer items over money by choosing the following option:
![Screenshot_1](https://user-images.githubusercontent.com/69223217/142604841-f707fd48-a4dc-4835-b75a-9b758296d759.png)

2. I'm not sure what you mean by enabling the server to publish tasks, can you give an example?

**Comment by 849025143** [comment]
Example:
1. The server will publish tasks at a specific time.
2. Tasks are competitive.
3. When someone completes it, the task will be deleted.
4. Like a medieval bounty for someone
5. Kill mobs ；Get items ；And other

**Comment by DavidTheExplorer** [comment]
1. Scheduled jobs aren't currently something EmployMe offers, but you will be able to make them once an API is released.
2. What do you mean by conpetitive? Right now the first player to complete a job gets the reward, then the job is deleted.
3. I don't understand. This is how the system works right now..?
4. What in minecraft do you consider as a medieval bounty? 
5. Killing mobs as jobs will be released in the future, but not now as there are many things to work on before progressing.

**Comment by 849025143** [comment]
yea, is this. —— I don't understand. This is how the system works right now..?
But published by the system.

**Comment by DavidTheExplorer** [comment]
Let me explain the current system: 

1. Let's say that you are a wealthy player who needs an Elytra.
2. You now run the command **/employment offer** and the first thing you do is to choose if you want to pay with money(e.g. _500$_) or with resources(e.g. _a full diamond armor_).
3. After choosing the reward **that you** will pay, You are asked in the chat _"what item you need?"_ so you reply with _"elytra:1"_
4. The job is posted, and can be completed by doing **/employment view** by anyone.
5. Once a player completes your job: The reward is transferred to him, the job is deleted, and your elytra can be accessed using **/employment myitems**.

Hopefully I satisfied your question about how EmployMe works **currently**, if you have more you're welcome to ask :)

**Comment by DavidTheExplorer** [comment]
@849025143 Hope I helped you? do you have more questions?

**Comment by 849025143** [comment]
> @849025143 Hope I helped you? do you have more questions?
yes,thank you.
I want to know if the required items can be customized.
to "itemName:amount"

**Comment by DavidTheExplorer** [comment]
> > @849025143 Hope I helped you? do you have more questions?
> > yes,thank you.
> > I want to know if the required items can be customized.
> > to "itemName:amount"

I'm working on adding NBT tags to the plugin.

**Comment by 849025143** [comment]
> > > @849025143 Hope I helped you? do you have more questions?
> > > yes,thank you.
> > > I want to know if the required items can be customized.
> > > to "itemName:amount"
> 
> I'm working on adding NBT tags to the plugin.

My question is over. Thank you for your answer. I'm looking forward to this feature.

**Comment by DavidTheExplorer** [comment]
> > > > @849025143 Hope I helped you? do you have more questions?
> > > > yes,thank you.
> > > > I want to know if the required items can be customized.
> > > > to "itemName:amount"
> > 
> > 
> > I'm working on adding NBT tags to the plugin.
> 
> My question is over. Thank you for your answer. I'm looking forward to this feature.

Good. Thank you very much for the suggestions!
