### ISSUE TITLE
"There was an error performing this command" when doing /employment view

### ISSUE THREAD

**Issue by HenrikoMagnifico** [DavidTheExplorer/EmployMe#92]
After having the plugin on my server for a couple days, all of a sudden[ this error started to pop up](https://www.toptal.com/developers/hastebin/nefiwudaqe.md) whenever any user tries to use /employment view. The only way to fix it is by completely deleting the plugin and re-installing it again.

Full latest.log:
[latest.log](https://github.com/DavidTheExplorer/EmployMe/files/7703906/latest.log)

Platform: PaperMC #68 (MC: 1.18.1)
Java Version: Java 17

**Comment by HenrikoMagnifico** [comment]
> Hello :)
> 
> 1. Which version of the plugin do you use? The most updated is 1.0.6
> 2. Can you send your jobs.yml config?
> 3. The plugin currently only supports 1.16 but that doesn't stop it from working on other versions, it's just not tested in 1.18

Thanks for your response! I'm using the latest version of the plugin, 1.0.6. Here is the jobs.yml file!
[jobs.txt](https://github.com/DavidTheExplorer/EmployMe/files/7714501/jobs.txt)

**Comment by DavidTheExplorer** [comment]
For some reason every goal appears as NULL, this shouldn't happen.
How did you create all these jobs? which item did you select as the goal? I need a step by step description.

**Comment by DavidTheExplorer** [comment]
@HenrikoMagnifico Hello? Any updates?

**Comment by DavidTheExplorer** [comment]
It looks like the problem was magically resolved.
